---
title: "AHR - Comparison"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(kableExtra)
```


```{r}
AHR_2019 <- rio::import("Copy of Final_AHR_Report .xlsx")


AHR_2019_disbursment <- AHR_2019 %>% rename(state = State,
                    SHA_miles = `SHA Miles`,
                    state_controlled_lane_miles = `State Controlled Lane Miles`, 
                    SHA_ratio = `SHA Ratio`, 
                    capital_disbursement = `Capital Disbursements`, 
                    maintenance_disbursement = `Maintenence Disbursements`, 
                    admin_disbursement = `Administrative Disbursements`,
                    total_disbursement = `Total Disbursements`,
                    rural_interstate_above_170 = `Rural Interstate Poor Condition, Number of Miles, IRI > 170`,
                    rural_interstate_total = `Rural Interstate Total Miles Measured`,
                    rural_OPA_above_220 = `Rural Other Principal Arterial Poor Condition Miles, IRI> 220`,
                    rural_OPA_total = `Rural Other Principal Arterial, Total`,
                    urban_interstate_above_170 = `Urban Interstate Poor Condition Miles, IRI > 170`,
                    urban_interstate_total = `Urban Interstate Total Reported`,
                   # urban_OPA_above_220 = `Urban Other Principal Arterial, Miles less than <220`,
                    urban_OPA_total = `Urban Other Principal Arterial, Total`,
                   total_fatalities = `Total Fatalities`,
                   rural_I_OFE_OPA_fatalities = `Rural - I - OFE - OPA - Total Fatalities`,
                   urban_I_OFE_OPA_fatalities = `Urban - I - OFE - OPA Total Fatalities`,
                   total_VMT = `Total VMT`,
                   rural_VMT = `Rural VMT`, 
                   urban_VMT = `Urban VMT`,
                   capital_disbursement_per_lm = `Capital Disbursements Per Lane Mile...31`,
                   maintenance_disbursement_per_lm = `Maintenence Disbursements Per Lane Mile...32`,
                   admin_disbursement_per_lm = `Admin Disbursements Per Lane Mile...33`,
                   total_disbursement_per_lm = `Total Disbursements Per Lane Miles...34`,
                   overall_score = `Overall Score`,
                   overall_score_rank = `Overall Rank`
                    ) %>% 
  select(state, Year, overall_score_rank, 
         total_disbursement_per_lm, 
         capital_disbursement_per_lm, 
         maintenance_disbursement_per_lm, 
         admin_disbursement_per_lm)
```

```{r}
AHR_2020 <- readRDS("AHR_2020.RDS")

AHR_2020_disbursment <- AHR_2020 %>% 
  mutate(Year = 2020) %>% 
  select(state, Year, overall_score_rank, 
         total_disbursement_per_lm, 
         capital_disbursement_per_lm, 
         maintenance_disbursement_per_lm, 
         admin_disbursement_per_lm)
```

## Changes 2019 - 2020
```{r, fig.width=4, fig.height=6}
disbursment19_20 <- rbind(AHR_2019_disbursment, AHR_2020_disbursment) %>% filter(state != "United States") 

changes19_20 <- disbursment19_20 %>% arrange(state) %>% 
  group_by(state) %>% 
  
  # calculate changes 2019 - 2020
  mutate(change_score = overall_score_rank - lead(overall_score_rank, order_by = Year),
         change_total_disbursement_per_lm = total_disbursement_per_lm - lead(total_disbursement_per_lm, order_by = Year),
         change_capital_disbursement_per_lm = capital_disbursement_per_lm - lead(capital_disbursement_per_lm, order_by = Year),
         change_maintenance_disbursement_per_lm = maintenance_disbursement_per_lm - lead(maintenance_disbursement_per_lm, order_by = Year),
         change_admin_disbursement_per_lm = admin_disbursement_per_lm - lead(admin_disbursement_per_lm, order_by = Year)
         ) %>% 
  select(8:12) %>% 
  drop_na()
  

kable(changes19_20, "html") %>%
kable_styling() %>%
scroll_box(height = "500px", width = "800px")
```

```{r, fig.width=10, fig.height=12}
lowerranks <- changes19_20 %>% filter(change_score < 0)

changes19_20 %>% 
  filter(change_score != 0) %>% 
  ggplot(aes(fct_reorder(state, change_score), change_score)) +
  geom_col(fill="darkgreen", alpha=.8, width=.5)+
  geom_col(data = lowerranks, fill="lightblue", alpha=.8, width=.5)+
  coord_flip() +
  labs(
    x = "",
    y= "Score",
    title = "Changes in overall ranking",
    subtitle = "38 states",
    caption = "Note: There are 12 states that maintain their overal rankings")  +
  theme_minimal()
```


```{r, results = 'asis',  fig.width=10, fig.height=12}
changes19_20 %>% 
  arrange(desc(change_score)) %>% filter(change_score >5) %>% 
  select(-change_total_disbursement_per_lm) %>% 
  pivot_longer(cols = 3:5,
               names_to = "category",
               values_to = "value") %>% 
  ggplot(aes(state, value, group = category)) +
  geom_col(aes(fill = category), position = position_dodge()) +
  scale_fill_brewer() +
  
  labs(
    x = "",
    y = "",
    title = "Top 5 states with the largest changes in overall ranking",
    subtitle = "")  +
  theme_minimal() +
  theme(
    legend.position = c(.95, .95),
    legend.justification = c("right", "top"),
    legend.box.just = "right") 
  
```

